version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - cd $PACKAGE_DIR
      - npm install
      - npm run build
artifacts:
  name: BUILD
  base-directory: $BUILD_DIR
  files:
    - '**/*'