version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - cd $PACKAGE_DIR
      - npm install
      # The magic command below uses jq to merge the existing package.json
      # with an object containing the correct homepage key
      - "cat package.json | jq '. |= . + { \"homepage\": \"./\" }' > tmp-package.json"
      - mv tmp-package.json package.json
      - |
        cat > build-env.sh << "EOF"
        touch .env
        IFS=',' read -ra LINES <<< "$ENV_VARS"
        for line in "${LINES[@]}"; do
          echo $line >> .env
        done
        EOF
      - bash build-env.sh
      - rm build-env.sh
      - npm run build
artifacts:
  name: BUILD
  base-directory: $BUILD_DIR
  files:
    - '**/*'